// Code generated by tool. DO NOT EDIT.
// app: todolist, biz: task

package errno

import (
	"github.com/crazyfrankie/frx/errorx/code"
)

const (
	ErrTaskNotFoundCode              = 122001
	errTaskNotFoundMessage           = "task not found"
	errTaskNotFoundNoAffectStability = true
)

func init() {

	code.Register(
		ErrTaskNotFoundCode,
		errTaskNotFoundMessage,
		code.WithAffectStability(!errTaskNotFoundNoAffectStability),
	)

}
