// Code generated by tool. DO NOT EDIT.
// app: todolist, biz: task

package types

import (
	"github.com/crazyfrankie/frx/errorx/code"
)

const (
	TaskNotFoundCode              = 122001
	taskNotFoundMessage           = "task not found"
	taskNotFoundNoAffectStability = true
)

func init() {

	code.Register(
		TaskNotFoundCode,
		taskNotFoundMessage,
		code.WithAffectStability(!taskNotFoundNoAffectStability),
	)

}
