// Code generated by tool. DO NOT EDIT.
// app: todolist, biz: user

package errno

import (
	"github.com/crazyfrankie/frx/errorx/code"
)

const (
	ErrUserNotFoundCode              = 111001
	errUserNotFoundMessage           = "user not found"
	errUserNotFoundNoAffectStability = true

	ErrEmailExistCode              = 111002
	errEmailExistMessage           = "email already exists"
	errEmailExistNoAffectStability = true

	ErrUniqueNameExistCode              = 111003
	errUniqueNameExistMessage           = "unique name already exists"
	errUniqueNameExistNoAffectStability = true

	ErrAuthFailedCode              = 111004
	errAuthFailedMessage           = "authentication failed"
	errAuthFailedNoAffectStability = true

	ErrEmailOrPasswordIncorrectCode              = 111005
	errEmailOrPasswordIncorrectMessage           = "email or password is incorrect"
	errEmailOrPasswordIncorrectNoAffectStability = true
)

func init() {

	code.Register(
		ErrUserNotFoundCode,
		errUserNotFoundMessage,
		code.WithAffectStability(!errUserNotFoundNoAffectStability),
	)

	code.Register(
		ErrEmailExistCode,
		errEmailExistMessage,
		code.WithAffectStability(!errEmailExistNoAffectStability),
	)

	code.Register(
		ErrUniqueNameExistCode,
		errUniqueNameExistMessage,
		code.WithAffectStability(!errUniqueNameExistNoAffectStability),
	)

	code.Register(
		ErrAuthFailedCode,
		errAuthFailedMessage,
		code.WithAffectStability(!errAuthFailedNoAffectStability),
	)

	code.Register(
		ErrEmailOrPasswordIncorrectCode,
		errEmailOrPasswordIncorrectMessage,
		code.WithAffectStability(!errEmailOrPasswordIncorrectNoAffectStability),
	)

}
