// Code generated by tool. DO NOT EDIT.
// app: todolist, biz: user

package types

import (
	"github.com/crazyfrankie/frx/errorx/code"
)

const (
	UserNotFoundCode              = 111001
	userNotFoundMessage           = "user not found"
	userNotFoundNoAffectStability = true

	EmailExistCode              = 111002
	emailExistMessage           = "email already exists"
	emailExistNoAffectStability = true

	UniqueNameExistCode              = 111003
	uniqueNameExistMessage           = "unique name already exists"
	uniqueNameExistNoAffectStability = true

	AuthFailedCode              = 111004
	authFailedMessage           = "authentication failed"
	authFailedNoAffectStability = true

	EmailOrPasswordIncorrectCode              = 111005
	emailOrPasswordIncorrectMessage           = "email or password is incorrect"
	emailOrPasswordIncorrectNoAffectStability = true
)

func init() {

	code.Register(
		UserNotFoundCode,
		userNotFoundMessage,
		code.WithAffectStability(!userNotFoundNoAffectStability),
	)

	code.Register(
		EmailExistCode,
		emailExistMessage,
		code.WithAffectStability(!emailExistNoAffectStability),
	)

	code.Register(
		UniqueNameExistCode,
		uniqueNameExistMessage,
		code.WithAffectStability(!uniqueNameExistNoAffectStability),
	)

	code.Register(
		AuthFailedCode,
		authFailedMessage,
		code.WithAffectStability(!authFailedNoAffectStability),
	)

	code.Register(
		EmailOrPasswordIncorrectCode,
		emailOrPasswordIncorrectMessage,
		code.WithAffectStability(!emailOrPasswordIncorrectNoAffectStability),
	)

}
