// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTask = "task"

// Task Task Table
type Task struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary Key ID" json:"id"` // Primary Key ID
	Content     string `gorm:"column:content;comment:Task Content" json:"content"`                       // Task Content
	UserID      int64  `gorm:"column:user_id;not null;comment:Associated User ID" json:"user_id"`        // Associated User ID
	DueTime     int64  `gorm:"column:due_time" json:"due_time"`
	Priority    string `gorm:"column:priority;not null;default:neither important or urgent;comment:Task priority level" json:"priority"` // Task priority level
	IsCompleted bool   `gorm:"column:is_completed;comment:is completed" json:"is_completed"`                                             // is completed
	CreatedAt   int64  `gorm:"column:created_at;not null;comment:Creation Time (Milliseconds)" json:"created_at"`                        // Creation Time (Milliseconds)
	UpdatedAt   int64  `gorm:"column:updated_at;not null;comment:Update Time (Milliseconds)" json:"updated_at"`                          // Update Time (Milliseconds)
	DeletedAt   int64  `gorm:"column:deleted_at;comment:Deletion Time (Milliseconds)" json:"deleted_at"`                                 // Deletion Time (Milliseconds)
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
